[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
base-sepolia = "https://base-sepolia-rpc.publicnode.com"
ethereum = "https://ethereum-rpc.publicnode.com"
base = "https://base-rpc.publicnode.com"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base-sepolia = { key = "${BASESCAN_API_KEY}" }